# Generated by Django 6.0.6 on 2026-07-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portDATA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonDATA',
            new_name='PersonalDATA',
        ),
    ]
