# Generated by Django 6.0.6 on 2026-07-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portDATA', '0002_rename_persondata_personaldata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalDATA',
            new_name='PersonDATA',
        ),
    ]
