# Generated by Django 6.0.6 on 2026-10-02 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portDATA', '0004_contactdata_otherprojdata_testimonialdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projdata',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='projdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projdata',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projdata',
            name='project_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='projdata',
            name='tech_stacks',
            field=models.ManyToManyField(related_name='projects', to='portDATA.techstack'),
        ),
    ]
